name: Compile Packages
on:
  release:
    types:
      - created
  push:
  pull_request:

permissions:
  contents: write
  id-token: write
  pages: write

jobs:
  pacman:
    runs-on: ubuntu-22.04
    container: archlinux
    steps:
      - uses: actions/checkout@v3
      - run: pacman -Syu --noconfirm base-devel git
      - run: makepkg -sf --noconfirm
        env:
          EUID: "1"
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.repository.name }}.Arch
          path: "*.pkg.tar.zst"
